[package]
name = "gorder"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Ladme/gorder"
keywords = ["gromacs", "molecular-dynamics"]
categories = ["command-line-utilities", "science"]
exclude = ["/tests"]

[dependencies]
backitup = "0.1.1"
groan_rs = { version = "0.9.0-dev.1", features = ["parallel"] }
colored = "2.1"
thiserror = "1.0.64"
derive_builder = "0.20.1"
getset = "0.1.3"
log = "0.4.22"
hashbrown = "0.14.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_yaml = "0.9.34"
indexmap = { version = "2.5.0", features = ["serde"] }
clap = { version = "4.5.18", features = ["derive"] }
colog = "1.3.0"
serde_valid = "0.25.0"

[dev-dependencies]
approx = "0.5.1"
file_diff = "1.0.0"
tempfile = "3.13.0"
