[package]
name = "gorder"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Ladme/gorder"
keywords = ["gromacs", "molecular-dynamics"]
categories = ["command-line-utilities", "science"]
exclude = ["/tests"]

[dependencies]
backitup = "0.1.1"
groan_rs = { version = "0.9.0-dev.1", features = ["parallel"] }
colored = "2.1"
thiserror = "1.0.63"
derive_builder = "0.20.0"
getset = "0.1.2"
log = "0.4.22"
hashbrown = "0.14.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_yaml = "0.9.34"
indexmap = { version = "2.5.0", features = ["serde"] }

[dev-dependencies]
approx = "0.5.1"
