[project]
name = "lipyphilic_benchmark"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "lipyphilic>=0.11.0",
    "mdanalysis>=2.8.0",
    "numpy<2",
]
