# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

class OrderMap:
    r"""
    Parameters for generating order maps.
    
    Parameters
    ----------
    output_directory : Optional[str]
        Directory where output files containing individual order maps will be saved.
    
    min_samples : Optional[int], default=1
        Minimum number of samples required in a grid tile to calculate the order parameter.
    
    dim : Optional[List[Union[str, List[float]]]]
        Span of the grid along the axes:
        - First span corresponds to the x-axis (for xy or xz plane) or z-axis (for yz plane).
        - Second span corresponds to the y-axis (for xy or yz plane) or z-axis (for xz plane).
        If not specified, the span is derived from the simulation box size of the input structure.
    
    bin_size : Optional[List[float]], default=[0.1, 0.1]
        Size of the grid bin along the axes:
        - First bin dimension corresponds to the x-axis (for xy or xz plane) or z-axis (for yz plane).
        - Second bin dimension corresponds to the y-axis (for xy or yz plane) or z-axis (for xz plane).
    
    plane : Optional[str]
        Plane in which the order maps are constructed. Allowed values: `xy`, `xz`, `yz`.
        If not specified, the plane is assumed to be perpendicular to the membrane normal.
    
    Raises
    ------
    ConfigError
        If `min_samples` <= 0, `bin_size` <= 0, any `dim` span is invalid (first value <= second),
        or if `plane` is not one of the allowed values (`xy`, `xz`, `yz`).
    """
    def __new__(cls, output_directory:typing.Optional[builtins.str]=None, min_samples:builtins.int=1, dim:typing.Optional[typing.List[typing.Union[builtins.str, typing.List[builtins.float]]]]=None, bin_size:typing.Sequence[builtins.float]=[0.10000000149011612, 0.10000000149011612], plane:typing.Optional[builtins.str]=None) -> OrderMap: ...

