name: Build Checks

on:
  workflow_dispatch:

jobs:
  linux-build:
    name: Build / Linux / ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            sudo apt-get install -y clang
          fi

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Set compiler environment
        if: matrix.compiler == 'clang'
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

  windows-build:
    name: Build / Windows / ${{ matrix.toolchain }}
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain: [msvc, gnu]
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC (msvc toolchain)
        if: matrix.toolchain == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup MinGW (gnu toolchain)
        if: matrix.toolchain == 'gnu'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-toolchain

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustc, cargo, rust-std
          override: true
      
      - name: Set Cargo Path
        run: echo "$USERPROFILE\.cargo\bin" >> $env:GITHUB_PATH

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          PATH: ${{ env.PATH }};${{ (matrix.toolchain == 'gnu' && 'C:\\msys64\\mingw64\\bin') || '' }};${{ env.HOME }}\\.cargo\\bin

  macos-build:
    name: Build / macOS / clang
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install cmake

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release